# Configuration Settings

def config():
    SETTINGS = {
        # HOW MANY DAYS OF INACTIVITY BEFORE A CHANNEL IS MARKED FOR ARCHIVING
        "EXPIRY_LIMIT" : 60,
        # HOW MANY DAYS BEFORE A MARKED CHANNEL IS AUTO-ARCHIVED
        "GRACE_PERIOD" : 7,
        # CHANNEL ID OF WHERE THE BOT WILL REPORT TO 
        "PRIVATE_CHANNEL_ID" : "C02HDPP5QUF",
    }

    return SETTINGS


