# Configuration Settings

def config():
    SETTINGS = {
        # HOW MANY DAYS OF INACTIVITY BEFORE A CHANNEL IS MARKED FOR ARCHIVING
        "EXPIRY_LIMIT" : 2,
        # HOW MANY DAYS BEFORE A MARKED CHANNEL IS AUTO-ARCHIVED
        "GRACE_PERIOD" : 0,
        # AMOUNT OF DAYS BEFORE BOT MAKES A SWEEP (SHOULD BE LOWER NUMBER THAN EXPIRY_LIMIT)
        "CHECK_INTERVAL" : 10,
        # CHANNEL ID OF WHERE THE BOT WILL REPORT TO
        "PRIVATE_CHANNEL_ID" : "C02HDPP5QUF",
        #privatechannel_Group = "C02HR74SWMS"
        #privatechannel_Solo = "C02HDPP5QUF"
    }

    return SETTINGS


